### ISSUE TITLE
not working - Renderdoc v1.12

### ISSUE THREAD

**Issue by Drury13** [FXTD-ODYSSEY/renderdoc2fbx#1]
extension installed and loaded, save box opens but doesnt create file when saved

**Comment by FXTD-ODYSSEY** [comment]
Any error pop up ?
Just nothing happended ?

**Comment by zxsama** [comment]
Hello, I have the same problem. Here is the error message.
I try to debug and found no value in idx_dict["POSITION"]



EXTN 017300: [17:18:51]              unknown(   0) - Error   - Traceback (most recent call last):
EXTN 017300: [17:18:51]              unknown(   0) - Error   -   File "C:/Users/xxx/AppData/Roaming/qrenderdoc/extensions\exporter\fbx\__init__.py", line 436, in prepare_export
EXTN 017300: [17:18:51]              unknown(   0) - Error   -     pyrenderdoc.Replay().BlockInvoke(partial(export_fbx, save_path, meshInputs))
EXTN 017300: [17:18:51]              unknown(   0) - Error   -   File "C:/Users/xxx/AppData/Roaming/qrenderdoc/extensions\exporter\fbx\__init__.py", line 217, in export_fbx
EXTN 017300: [17:18:51]              unknown(   0) - Error   -     min_poly = min(polygons)
EXTN 017300: [17:18:51]              unknown(   0) - Error   - ValueError: min() arg is an empty sequence
EXTN 017300: [17:18:51]              unknown(   0) - Error   -

**Comment by FXTD-ODYSSEY** [comment]
this is the problem of the attribute name.
My FBX export Extension base on Unity buffer attribute name before.
right now , I add a user attriubte input dialog for specific attribute export.

![image](https://user-images.githubusercontent.com/40897360/114260490-c5dd5f00-9a07-11eb-8833-801031db985c.png)

I think with the correct name of the attribute will fix the problem.

**Comment by ArtLeav** [comment]
Hi, just get this at any try
![qrenderdoc_1e4nO1M03z](https://user-images.githubusercontent.com/93773742/140510097-a5ed7a75-c164-4f87-b87c-f5d03bb97556.png)
