### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by zeak6464** [FXTD-ODYSSEY/renderdoc2fbx#4]
![Screenshot 2021-08-29 124534](https://user-images.githubusercontent.com/2738141/131258462-93051275-f532-4dc2-a693-01d7665556b4.png)
this is what it gives me when i try to export.

**Comment by FXTD-ODYSSEY** [comment]
Please send the error message , So I can trace the problem

**Comment by zeak6464** [comment]
where do i find the error log at ?

**Comment by FXTD-ODYSSEY** [comment]
Can you share your rdc file and point out what you do so that I can reproduce your error

**Comment by Sola-Solo** [comment]
> ![Screenshot 2021-08-29 124534](https://user-images.githubusercontent.com/2738141/131258462-93051275-f532-4dc2-a693-01d7665556b4.png)
> this is what it gives me when i try to export.

After RenderDoc version 1.11, the signature of the function CreateToplevelWidget has been changed.
Please check the details: [Here](https://renderdoc.org/docs/python_api/qrenderdoc/extensions.html?highlight=createtoplevelwidget#qrenderdoc.MiniQtHelper.CreateToplevelWidget)

You can modify the **query_dialog.py** to make it available to the latest version of RenderDoc
<img width="501" alt="QQ拼音截图20210921144158" src="https://user-images.githubusercontent.com/35339645/134124766-d7559c94-f91f-4b93-976b-f7c9e4ddfe59.png">
.

**Comment by zeak6464** [comment]
> > ![Screenshot 2021-08-29 124534](https://user-images.githubusercontent.com/2738141/131258462-93051275-f532-4dc2-a693-01d7665556b4.png)
> > this is what it gives me when i try to export.
> 
> After RenderDoc version 1.11, the signature of the function CreateToplevelWidget has been changed.
> Please check the details: [Here](https://renderdoc.org/docs/python_api/qrenderdoc/extensions.html?highlight=createtoplevelwidget#qrenderdoc.MiniQtHelper.CreateToplevelWidget)
> 
> You can modify the **query_dialog.py** to make it available to the latest version of RenderDoc
> <img alt="QQ拼音截图20210921144158" width="501" src="https://user-images.githubusercontent.com/35339645/134124766-d7559c94-f91f-4b93-976b-f7c9e4ddfe59.png">
> .
[test.zip](https://github.com/FXTD-ODYSSEY/renderdoc2fbx/files/7220677/test.zip)

this didnt work.

**Comment by Sola-Solo** [comment]
The script I modified is suitable for RenderDoc V1.15 without any errors. [fbxScript.zip](https://github.com/FXTD-ODYSSEY/renderdoc2fbx/files/7222848/fbxOutput.zip)
<img width="960" alt="QQ拼音截图20210924115630" src="https://user-images.githubusercontent.com/35339645/134618943-34d1079f-dbd4-4c0c-abd4-37885b1c799d.png">
<img width="555" alt="2" src="https://user-images.githubusercontent.com/35339645/134618950-35b577ab-736d-4ce6-9933-abc3172d404a.png">
